### PR TITLE
update versions and switch to dynamic project versioning

### PR DESCRIPTION
**Pull request by razvan**
- **chore: use package name and version from pyproject.toml**
- **chore: use 'with' for convenience**
- **index on chore/beku-nix-version: b875089 chore: use 'with' for convenience**
- **Update readme**

### CODE REVIEW

**Review by adwk67 — APPROVED** [review]
lgtm!

**Comment by NickLarsenNZ** [comment]
This breaks nix (as previously discussed).

Nix reads the version from a TOML. But this PR moves the version into a python file which complicates things for Nix:

https://github.com/stackabletech/beku.py/blob/2f0174c606e91a8631af6595320be9efa36d6206/beku.nix#L4

I will see whether we can get the version from the python file in the cleanest way, otherwise version.py could read it from a TOML or something.

**Comment by razvan** [comment]
> This breaks Nix (as previously discussed).

I remember now. Sorry. I'm fine with duplicating the version string somewhere so that nix is happy again. Other Python nix packages do the same.

**Comment by NickLarsenNZ** [comment]
No worries. I would rather it be defined in one place to save it getting all out of whack in future updates.

I have the following ideas:
- See if pyproject.nix is able to handle dynamic versions... then whatever it produces gets passed to `buildPythonApplication` (most ideal).
- Evaluate `version.py` and get the version (not bad, but I don't know how to do it yet).
- Grep-and-chop `version.py` (least ideal, prone to edge-case failures and additional maintenance of patterns).

**Pull request merged**
